#Author: Adam Zelezny
#Date: 2026-07-08

from pathlib import Path
import numpy as np
import scanpy as sc
INPUT_FILE = Path('projects/differences/outputs/normalized/combined_normalized.h5ad')
OUTPUT_FILE = Path('projects/differences/outputs/log_transformed/combined_log1p.h5ad')
OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
print('\nLoading normalized dataset...')
adata = sc.read_h5ad(INPUT_FILE)
print(adata)
print("\nSaving normalized matrix into .layers['normalized']...")
adata.layers['normalized'] = adata.X.copy()
print('Done.')
print('\n============================================================')
print('BEFORE LOG TRANSFORMATION')
print('============================================================')
values = adata.X
print(f'Minimum value : {values.min():.4f}')
print(f'Maximum value : {values.max():.4f}')
sample = values[:100, :100].toarray()
print('\nSample statistics:')
print(f'Mean : {sample.mean():.4f}')
print(f'Std  : {sample.std():.4f}')
print('\nApplying log1p transformation...')
sc.pp.log1p(adata)
print('Done.')
print('\n============================================================')
print('AFTER LOG TRANSFORMATION')
print('============================================================')
values = adata.X
print(f'Minimum value : {values.min():.4f}')
print(f'Maximum value : {values.max():.4f}')
sample = values[:100, :100].toarray()
print('\nSample statistics:')
print(f'Mean : {sample.mean():.4f}')
print(f'Std  : {sample.std():.4f}')
print('\n============================================================')
print('VERIFY DATA REPRESENTATIONS')
print('============================================================')
print('Layers present:')
print(list(adata.layers.keys()))
print('\nStored representations:')
print("- layers['counts']      -> raw integer counts")
print("- layers['normalized']  -> normalized counts")
print('- X                     -> log1p(normalized counts)')
print('\nSaving log-transformed dataset...')
adata.write_h5ad(OUTPUT_FILE)
print(f'\nSaved to:\n{OUTPUT_FILE}')
